home_api/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from home_api.settings import MEDIA_ROOT, STATIC_ROOT
from home_api.views import index

urlpatterns = [
    path('', index, name='index'),
    path('weather/', include('weather.urls')),
    path('wip/', include('work_in_progress.urls')),
    path('postcards/', include('postcards.urls')),
    path('todo_mobile/', include('todo_mobile.urls')),
    path('travel/', include('travel.urls')),
    path('admin/', admin.site.urls),
    re_path(r"media/(?P<path>.*)$", serve, kwargs={'document_root': MEDIA_ROOT}),
    re_path(r"static/(?P<path>.*)$", serve, kwargs={'document_root': STATIC_ROOT})
]

postcards/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'postcards'
urlpatterns = [
    path('login', views.log_in, name='login'),
    path('logout', views.log_out, name='logout'),

    # отображение страницы редактирования.
    path('', views.PostcardsListView.as_view(), name='index'),
    # отображение страницы на добавление открытки
    path('add', login_required(views.PostcardCreateView.as_view(), login_url='/postcards/login'), name='add'),
    path('<int:id>/edit', login_required(views.PostcardEditView.as_view(), login_url='/postcards/login'), name='edit'),
    path('<int:id>/delete', login_required(views.PostcardDeleteView.as_view(), login_url='/postcards/login'),
         name='delete'),
    path('library', views.LibraryListView.as_view(), name='library'),
    path('library/add', views.library_add, name='library_add'),
    path('library/<int:id>/delete', views.library_delete, name='library_delete'),
    path('address/<int:id>/add', views.add_address, name='address_recipient'),
]

travel/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import PlaceViewSet, index


router = routers.DefaultRouter()
router.register(r'places', PlaceViewSet)

app_name = 'travel'
urlpatterns = [
    path('', index, name='index'),
    path('api/', include(router.urls)),
]

postcards/models.py
import datetime

from django.db import models


class Postcard(models.Model):
    image = models.ImageField(upload_to='postcard', verbose_name='лицевая сторона')
    sender = models.CharField(max_length=50, verbose_name='имя отправителя')
    country = models.CharField(max_length=50, verbose_name='страна отправления')
    travel_time = models.IntegerField(verbose_name='дней в пути')
    date_receiving = models.DateField(verbose_name='дата получения открытки', default=datetime.date.today())


    class Meta:
        verbose_name = 'Полученная открытка'
        verbose_name_plural = 'Полученные открытки'


class Library(models.Model):
    image = models.ImageField(upload_to='library', verbose_name='картинка')
    is_reserved = models.BooleanField(default=False)
    is_sent = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Открытка для отправления'
        verbose_name_plural = 'Открытки для отправления'


class Address(models.Model):
    postcard = models.OneToOneField(Library, on_delete=models.RESTRICT)
    name = models.CharField(max_length=50, verbose_name='ФИО получателя')
    address = models.CharField(max_length=70, verbose_name='адрес получутеля')
    postcode = models.CharField(max_length=8, verbose_name='индекс')

postcards/forms.py
from django.forms import ImageField, CharField, IntegerField, ChoiceField, Form, PasswordInput, ModelForm, DateField

from .models import Postcard


def build_country_choices():
    c = ['Россия', 'Германия', 'Нидерланды']
    return [(x, x) for x in c]


class PostcardForm(ModelForm):
    image = ImageField(label='фотка')
    sender = CharField(max_length="50", label="отправитель")
    country = ChoiceField(label='страна', choices=build_country_choices)
    travel_time = IntegerField(label="время в пути")
    date_receiving = DateField(label='дата получения')

    class Meta:
        model = Postcard
        fields = ('image', 'sender', 'country', 'travel_time', 'date_receiving')


class LibraryAddForm(Form):
    image = ImageField(label='фотка')


class AddressAddForm(Form):
    name = CharField(max_length="70", label='имя получателя')
    postcode = CharField(max_length="30", label='postcode')
    address = CharField(max_length="70", label='адрес')


class LoginForm(Form):
    username = CharField(label='Логин', max_length=40)
    password = CharField(label='Пароль', widget=PasswordInput, max_length=40)

postcards/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView, View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .models import Postcard, Library, Address
from .forms import PostcardForm, LibraryAddForm, AddressAddForm, LoginForm


def log_in(request):
    if request.user.is_authenticated:
        return redirect('postcards:index')

    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'postcards/login.html', {'form': form})

    form = LoginForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('postcards:index')
    return render(request, 'postcards/login.html', {'form': form})


def log_out(request):
    logout(request)
    return redirect('postcards:index')


class PostcardsListView(ListView):
    model = Postcard
    context_object_name = 'postcards'
    paginate_by = 5
    ordering = ['id']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class PostcardCreateView(CreateView):
    template_name = 'postcards/add.html'
    form_class = PostcardForm
    success_url = '/postcards'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PostcardEditView(UpdateView):
    model = Postcard
    form_class = PostcardForm
    success_url = '/postcards'
    pk_url_kwarg = 'id'
    template_name_suffix = '_edit_form'

    def get_context_data(self, *args,  **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PostcardDeleteView(View):
    def get(self, *args, **kwargs):
        f = Postcard.objects.get(id=self.kwargs['id'])
        if self.request.method == 'GET':
            f.delete()
            return redirect('postcards:index')


def delete(request, id):
    f = Postcard.objects.get(id=id)
    if request.method == 'GET':
        f.delete()
        return redirect('postcards:index')


class LibraryListView(ListView):
    model = Library
    context_object_name = 'postcards'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


def library_delete(request, id):
    f = Library.objects.get(id=id)
    if request.method == 'GET':
        f.delete()
        return redirect('postcards:library')


def library_add(request):
    if request.method == 'GET':
        form = LibraryAddForm()
        return render(request, 'postcards/library/add.html', {'form': form})
    if request.method == 'POST':
        form = LibraryAddForm(request.POST, request.FILES)
        if form.is_valid():
            l = Library()
            l.image = form.cleaned_data['image']
            l.save()
            return redirect('postcards:library')
        return render(request, 'postcards/library/add.html', {'form': form})


def add_address(request, id):
    if request.method == 'GET':
        p = Library.objects.get(id=id)
        form = AddressAddForm()
        return render(request, 'postcards/address.html', {'form': form, 'postcard': p})
    if request.method == 'POST':
        form = AddressAddForm(request.POST)
        lp = Library.objects.get(id=id)
        if form.is_valid():
            address = Address()
            address.name = form.cleaned_data['name']
            address.address = form.cleaned_data['address']
            address.postcode = form.cleaned_data['postcode']
            address.postcard_id = lp.id
            address.save()

            lp.is_reserved = True
            lp.save()

            return redirect('postcards:library')
    return render(request, 'postcards/address.html', {'form': None, 'postcard': None})

postcards/templates/postcards/add.html
{% extends 'postcards/base.html' %}
{% block header %}
    <h1 class="ui header"> Добавление открытки</h1>
{% endblock header %}
{% block content %}
    <div class="ui two column container grid">
        <div class="column">
            <form  class="ui form" method="post" enctype="multipart/form-data" action="{% url 'postcards:add' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавление открытки" class="small ui button secondary">

</form>
             <a href="{% url 'postcards:index' %}"><button class="small ui button">назад</button></a>
        </div>
    </div>

{% endblock content %}

postcards/templates/postcards/address.html
{% extends 'postcards/base.html' %}
{% block header %}
    <h1 class="ui header"> Добавление адреса</h1>
{% endblock header %}
{% block content %}
    <div class="ui two column container grid">
        <div class="column">
            {% if postcard.image %}
                <div class="ui image" style="cursor: pointer;">
                    <img src="{{ postcard.image.url }}" style="max-height: 300px">
                </div>
            {% endif %}
            <form  class="ui form" method="post"
                   enctype="multipart/form-data"
                   action="{% url 'postcards:address_recipient' postcard.id %}">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Отправка адреса" class="small ui button secondary">
            </form>
            <a href="{% url 'postcards:library' %}">
                <button class="small ui button">к библиотеке открыток</button>
            </a>
        </div>
    </div>

{% endblock content %}

postcards/templates/postcards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
<link rel="stylesheet" href="{% static '/postcards/semantic/semantic.min.css' %}">
<script src="{% static '/postcards/js/jquery-2.1.3.min.js' %}"></script>
<script src="{% static '/postcards/semantic/semantic.min.js' %}"></script>

</head>
<body style="background-color: lightslategrey">
{% block header %}
    <h1>Входящие откртытки</h1>
{% endblock header %}
{% block content %}
{% endblock content %}
</body>
</html>

postcards/templates/postcards/edit.html
{% extends 'postcards/base.html' %}
{% block header %}
    <h1 class="ui header"> {{ title }}</h1>
{% endblock header %}
{% block content %}
    <div class="ui two column container grid">
        <div class="column">
            <form  class="ui form" method="post" enctype="multipart/form-data" action="{% url 'postcards:edit' postcard.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Редактировать" class="ui button primary">

</form>
             <a href="{% url 'postcards:index' %}"><button class="ui button">Назад</button></a>
        </div>
    </div>

{% endblock content %}

postcards/templates/postcards/index.html
{% extends 'postcards/base.html' %}
{% block header %}
   <h1 class="ui header" style="color: #4f20b5;font-size: 4em;text-align: center">Открыточная</h1>
{% endblock header %}
{% block content %}
        {% if user.is_authenticated %}
    <a href="{% url 'postcards:add' %}">
         <button class="small ui button secondary">Добавить новую входящую открытку</button>
    </a>
    {% endif %}

    <a href="{% url 'postcards:library' %}">
            <button class="small ui button secondary">Открытки к отправке</button>
    </a>
    {% if user.is_authenticated %}
        <a href="{% url 'postcards:logout' %}" style="color: white">Выход</a>
    {% else %}
        <a href="{% url 'postcards:login' %}" style="color: white">Вход</a>
    {% endif %}

<div class="ui grid container aligned center">

    {% for postcard in postcards %}
        <div class="ui card" style="margin: 15px; background-color: lightgrey">
            {% if postcard.image %}
                <div class="ui image" style="cursor: pointer;">
                 <img src="{{ postcard.image.url }}" style="max-height: 300px">
                </div>
            {% endif %}
            <div class="content">
                <div class="description">Отправитель: {{ postcard.sender }}</div>
                <div class="description">Страна: {{ postcard.country }}</div>
            </div>
            <div class="extra content">Дней в пути: {{ postcard.travel_time }}</div>
            <div class="extra centent">Дата получения: {{ postcard.date_receiving }}</div>
            <div class="extra content">
                {% if user.is_authenticated %}
                <a href="{% url 'postcards:edit' postcard.id %}">
                    <i class="pencil alternate icon"></i>
                </a>
                <a href="{% url 'postcards:delete' postcard.id %}">
                    <i class="trash alternate icon"></i>
                </a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

postcards/templates/postcards/library_list.html
{% extends 'postcards/base.html' %}
{% block header %}

    <h1 class="ui header" style="color: #4f20b5;font-size: 4em;text-align: center">Доступные к отправке</h1>

{% endblock header %}
{% block content %}
    <a href="{% url 'postcards:index' %}">
        <button class="small ui button secondary">к входящим открыткам</button>
    </a>
    {% if user.is_authenticated %}
    <a href="{% url 'postcards:library_add' %}">
        <button class="small ui button secondary">Добавить новую открытку</button>
    </a>
    {% endif %}
    <div class="ui grid container aligned center">

        {% for postcard in postcards %}

            <div class="ui card" style="margin: 15px; background-color: lightgrey">
                {% if postcard.image %}
                    <div class="ui image" style="cursor: pointer;">
                        <img src="{{ postcard.image.url }}" style="max-height: 300px">
                    </div>
                {% endif %}
            {% if not postcard.is_reserved %}
                <a href="{% url 'postcards:address_recipient' postcard.id %}">
                    <button class="small ui button secondary">Адрес</button>
                </a>
            {% endif %}

            <div class="extra content">
                {% if not postcard.is_reserved %}
                        {% if user.is_authenticated %}

                    <a href="{% url 'postcards:library_delete' postcard.id %}">
                        <i class="trash alternate icon"></i>
                    </a>
                            {% endif %}
                {% endif %}
                </div>
            </div>
        {% endfor %}

{% endblock content %}

postcards/templates/postcards/login.html
{% extends 'postcards/base.html' %}

{% block content %}
    <div class="ui five column doubling stackable grid container">
        <div class="column"></div>
        <div class="column"></div>
        <div class="column">
            <form action="{% url 'postcards:login' %}" method="post" class="ui form">
                {% csrf_token %}
                <div class="field {{ form.username.errors|yesno:'error,' }}">
                    <label>{{ form.username.label }}</label>
                    {{ form.username }}
                    {% if form.username.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.username.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="field {{ form.password.errors|yesno:'error,' }}">
                    <label>{{ form.password.label }}</label>
                    {{ form.password }}
                    {% if form.password.errors %}
                        <div class="ui pointing red basic label">
                            {{ form.password.errors }}
                        </div>
                    {% endif %}
                </div>
                <div>
                    <button class="ui button" type="submit">Вход</button>
                </div>
            </form>
        </div>
    </div>
    </div>
{% endblock content %}

postcards/templates/postcards/postcard_edit_form.html
{% extends 'postcards/base.html' %}
{% block header %}
    <h1 class="ui header"> {{ title }}</h1>
{% endblock header %}
{% block content %}
    <div class="ui two column container grid">
        <div class="column">
            <form  class="ui form" method="post" enctype="multipart/form-data" action="{% url 'postcards:edit' postcard.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Редактировать" class="ui button primary">

</form>
             <a href="{% url 'postcards:index' %}"><button class="ui button">Назад</button></a>
        </div>
    </div>

{% endblock content %}

postcards/templates/postcards/postcard_list.html
{% extends 'postcards/base.html' %}
{% block header %}
   <h1 class="ui header" style="color: #4f20b5;font-size: 4em;text-align: center">Открыточная</h1>
{% endblock header %}
{% block content %}
        {% if user.is_authenticated %}
    <a href="{% url 'postcards:add' %}">
         <button class="small ui button secondary">Добавить новую входящую открытку</button>
    </a>
    {% endif %}

    <a href="{% url 'postcards:library' %}">
            <button class="small ui button secondary">Открытки к отправке</button>
    </a>
    {% if user.is_authenticated %}
        <a href="{% url 'postcards:logout' %}" style="color: white">Выход</a>
    {% else %}
        <a href="{% url 'postcards:login' %}" style="color: white">Вход</a>
    {% endif %}

<div class="ui grid container aligned center">

    {% for postcard in postcards %}
        <div class="ui card" style="margin: 15px; background-color: lightgrey">
            {% if postcard.image %}
                <div class="ui image" style="cursor: pointer;">
                 <img src="{{ postcard.image.url }}" style="max-height: 300px">
                </div>
            {% endif %}
            <div class="content">
                <div class="description">Отправитель: {{ postcard.sender }}</div>
                <div class="description">Страна: {{ postcard.country }}</div>
            </div>
            <div class="extra content">Дней в пути: {{ postcard.travel_time }}</div>
            <div class="extra centent">Дата получения: {{ postcard.date_receiving }}</div>
            <div class="extra content">
                {% if user.is_authenticated %}
                <a href="{% url 'postcards:edit' postcard.id %}">
                    <i class="pencil alternate icon"></i>
                </a>
                <a href="{% url 'postcards:delete' postcard.id %}">
                    <i class="trash alternate icon"></i>
                </a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>
<div class="pagination" STYLE="color: #EAE7FF">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock content %}