home_api/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from home_api.settings import MEDIA_ROOT, STATIC_ROOT
from home_api.views import index

urlpatterns = [
    path('', index, name='index'),
    path('weather/', include('weather.urls')),
    path('wip/', include('work_in_progress.urls')),
    path('postcards/', include('postcards.urls')),
    path('todo_mobile/', include('todo_mobile.urls')),
    path('travel/', include('travel.urls')),
    path('admin/', admin.site.urls),
    re_path(r"media/(?P<path>.*)$", serve, kwargs={'document_root': MEDIA_ROOT}),
    re_path(r"static/(?P<path>.*)$", serve, kwargs={'document_root': STATIC_ROOT})
]

travel/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import PlaceViewSet, index


router = routers.DefaultRouter()
router.register(r'places', PlaceViewSet)

app_name = 'travel'
urlpatterns = [
    path('', index, name='index'),
    path('api/', include(router.urls)),
]

work_in_progress/model/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy
from . import views

LOGIN_URL = reverse_lazy('wip:login')

app_name = 'model'
urlpatterns = [
    # model
    path('add', login_required(views.WipModelCreate.as_view(), login_url=LOGIN_URL), name='add_model'),
    path('<str:username>', views.WipUserModels.as_view(), name='models'),
    path('<int:model_id>/edit', login_required(views.WipModelUpdate.as_view(), login_url=LOGIN_URL), name='edit_model'),
    path('<int:model_id>/delete', views.delete_model, name='delete_model'),

    # progress
    path('<str:username>/<int:model_id>/progress', views.WipModelProgress.as_view(), name='progress'),
    path('<str:username>/<int:model_id>/progress/add',
         login_required(views.WipModelProgressCreate.as_view(), login_url='/wip/accounts/login'),
         name='add_progress'),
    path('<str:username>/<int:model_id>/progress/<int:progress_id>/edit',
         login_required(views.WipModelProgressUpdate.as_view(), login_url='/wip/accounts/login'),
         name='edit_progress'),
    path('<str:username>/<int:model_id>/progress/<int:progress_id>/delete',
         views.delete_progress, name='delete_progress'),

    # update status actions
    path('<str:username>/<int:model_id>/status/<str:next_status>',
         login_required(views.WipModelStatusActions.as_view(), login_url='/wip/accounts/login'),
         name='model_status_action'),
]

work_in_progress/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy, include

# from rest_framework import routers
from rest_framework_nested import routers
from knox import views as knox_views

from . import views

LOGIN_URL = reverse_lazy('wip:login')

router = routers.DefaultRouter()
router.register(r"models", views.ApiWipModelsViewSet)
models_router = routers.NestedDefaultRouter(router, r'models', lookup='model')
models_router.register(r'progress', views.ApiWipModelProgressViewSet, basename='models-progress')
models_router.register(r'images', views.ApiWipModelImagesViewSet, basename='models-images')

router.register(r"statuses", views.ApiWipUserModelStatusesViewSet)
router.register(r"model-groups", views.ApiWipModelGroupViewSet)
router.register(r"bs-categories", views.ApiWipBattleScribeCategoryViewSet)
router.register(r"bs-units", views.ApiWipBattleScribeUnitsViewSet)
router.register(r"kill-teams", views.ApiWipKillTeamViewSet)

app_name = 'wip'
urlpatterns = [
    # api
    path('api/auth/login/', views.ApiWipLoginView.as_view(), name='knox_login'),
    path('api/auth/logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
    path('api/auth/logoutall/', knox_views.LogoutAllView.as_view(), name='knox_logoutall'),
    path('api/', include(router.urls)),
    path('api/', include(models_router.urls)),

    # common paths
    path('accounts/login/', views.WipLoginView.as_view(), name='login'),
    path('accounts/logout', views.log_out, name='logout'),
    path('accounts/register', views.WipRegisterView.as_view(), name='register'),
    path('about', views.about, name='about'),

    # index
    path('', views.WipIndexView.as_view(), name='index'),
    # inventory
    path('inventory',
         login_required(views.WipUserInventory.as_view(), login_url='/wip/accounts/login'),
         name='inventory'),
    path('inventory/manage',
         login_required(views.WipUserInventoryManage.as_view(), login_url='/wip/accounts/login'),
         name='inventory_manage'),
    # manage
    path('manage',
         login_required(views.manage, login_url='/wip/accounts/login'),
         name='manage'),
    # manage status_group
    path('manage/status_group/list',
         login_required(views.WipUserStatusGroupManage.as_view(), login_url='/wip/accounts/login'),
         name='manage_status_group_list'),
    path('manage/status_group/add',
         login_required(views.WipUserStatusGroupManageCreate.as_view(), login_url='/wip/accounts/login'),
         name='manage_status_group_add'),
    path('manage/status_group/<int:status_group_id>/edit',
         login_required(views.WipUserStatusGroupManageUpdate.as_view(), login_url='/wip/accounts/login'),
         name='manage_status_group_edit'),
    path('manage/status_group/<int:status_group_id>/delete',
         login_required(views.delete_user_status_group, login_url='/wip/accounts/login'),
         name='manage_status_group_delete'),

    # manage status
    path('manage/status/list',
         login_required(views.WipUserStatusManage.as_view(), login_url='/wip/accounts/login'),
         name='manage_status_list'),
    path('manage/status/add',
         login_required(views.WipUserStatusManageCreate.as_view(), login_url='/wip/accounts/login'),
         name='manage_status_add'),
    path('manage/status/<int:status_id>/edit',
         login_required(views.WipUserStatusManageUpdate.as_view(), login_url='/wip/accounts/login'),
         name='manage_status_edit'),
    path('manage/status/<int:status_id>/delete',
         login_required(views.delete_user_status, login_url='/wip/accounts/login'),
         name='manage_status_delete'),

    # manage model group
    path('manage/model_group/list',
         login_required(views.WipUserModelGroupManage.as_view(), login_url='/wip/accounts/login'),
         name='manage_model_group_list'),
    path('manage/model_group/add',
         login_required(views.WipUserModelGroupManageCreate.as_view(), login_url='/wip/accounts/login'),
         name='manage_model_group_add'),
    path('manage/model_group/<int:model_group_id>/edit',
         login_required(views.WipUserModelGroupManageUpdate.as_view(), login_url='/wip/accounts/login'),
         name='manage_model_group_edit'),
    path('manage/model_group/<int:model_group_id>/delete',
         login_required(views.delete_user_model_group, login_url='/wip/accounts/login'),
         name='manage_model_group_delete'),

    # model
    path('<str:username>/model', views.WipUserModels.as_view(), name='models'),
    path('model/add',
         login_required(views.WipModelCreate.as_view(), login_url=LOGIN_URL),
         name='add_model'),
    path('model/<int:model_id>/edit',
         login_required(views.WipModelUpdate.as_view(), login_url=LOGIN_URL),
         name='edit_model'),
    path('model/<int:model_id>/delete', views.delete_model, name='delete_model'),

    # progress
    path('<str:username>/model/<int:model_id>/progress', views.WipModelProgress.as_view(), name='progress'),
    path('<str:username>/model/<int:model_id>/progress/add',
         login_required(views.WipModelProgressCreate.as_view(), login_url='/wip/accounts/login'),
         name='add_progress'),
    path('<str:username>/model/<int:model_id>/progress/<int:progress_id>/edit',
         login_required(views.WipModelProgressUpdate.as_view(), login_url='/wip/accounts/login'),
         name='edit_progress'),
    path('<str:username>/model/<int:model_id>/progress/<int:progress_id>/delete',
         views.delete_progress, name='delete_progress'),

    # update status actions
    path('<str:username>/model/<int:model_id>/<str:next_status>',
         login_required(views.WipModelStatusActions.as_view(), login_url='/wip/accounts/login'),
         name='model_status_action'),
]

postcards/models.py
import datetime

from django.db import models


class Postcard(models.Model):
    image = models.ImageField(upload_to='postcard', verbose_name='лицевая сторона')
    sender = models.CharField(max_length=50, verbose_name='имя отправителя')
    country = models.CharField(max_length=50, verbose_name='страна отправления')
    travel_time = models.IntegerField(verbose_name='дней в пути')
    date_receiving = models.DateField(verbose_name='дата получения открытки', default=datetime.date.today())


    class Meta:
        verbose_name = 'Полученная открытка'
        verbose_name_plural = 'Полученные открытки'


class Library(models.Model):
    image = models.ImageField(upload_to='library', verbose_name='картинка')
    is_reserved = models.BooleanField(default=False)
    is_sent = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Открытка для отправления'
        verbose_name_plural = 'Открытки для отправления'


class Address(models.Model):
    postcard = models.OneToOneField(Library, on_delete=models.RESTRICT)
    name = models.CharField(max_length=50, verbose_name='ФИО получателя')
    address = models.CharField(max_length=70, verbose_name='адрес получутеля')
    postcode = models.CharField(max_length=8, verbose_name='индекс')

weather/models.py
from django.db import models


class Measure(models.Model):
    date = models.DateTimeField("Дата замера", null=False, blank=False)
    temperature = models.FloatField("Температура")
    humidity = models.FloatField("Влажность")

    def __str__(self):
        return "Measure(%d, date=%s, temp=%.2f, hum=%.2f)" % (self.id, self.date.strftime("%d-%m-%Y %H:%M:%S%z"), self.temperature, self.humidity)

work_in_progress/battlescribe/models.py
from django.db import models


class KillTeam(models.Model):
    name = models.CharField(verbose_name="Название", max_length=500)

    class Meta:
        verbose_name = "Истребительная команда"
        verbose_name_plural = "Истребительная команда"

    def __str__(self):
        return self.name


class KillTeamOperative(models.Model):
    kill_team = models.ForeignKey(KillTeam, verbose_name="Команда", on_delete=models.RESTRICT)
    name = models.CharField(verbose_name="Название", max_length=500)

    class Meta:
        verbose_name = "Оперативник"
        verbose_name_plural = "Оперативники"

    def __str__(self):
        return self.name


class BSCategory(models.Model):
    """
    Категория прочитананя из каталога данных BattleScribe
    """
    name = models.CharField(verbose_name="Название", max_length=500)
    source = models.CharField(verbose_name="Источник", max_length=500)

    class Meta:
        verbose_name = "Категория BattleScribe"
        verbose_name_plural = "Категории BattleScribe"

    def __str__(self):
        return "%s(%s)" % (self.name, self.source)

    def __unicode__(self):
        return "%s(%s)" % (self.name, self.source)


class BSUnit(models.Model):
    """
    Юнит прочитанный из каталога BattleScribe
    """
    name = models.CharField(verbose_name="Название", max_length=500)
    bs_category = models.ForeignKey(BSCategory, on_delete=models.RESTRICT, verbose_name="Тип", null=True)

    class Meta:
        verbose_name = "Юнит BattleScribe"
        verbose_name_plural = "Юниты BattleScribe"

    def __str__(self):
        return "%s (%s)" % (self.name, self.bs_category.name)

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.bs_category.name)

work_in_progress/inventory/models.py
from django.contrib.auth.models import User
from django.db import models


class PaintVendor(models.Model):
    name = models.CharField(verbose_name="Производитель", max_length=300)

    class Meta:
        verbose_name = "Вендор краски"
        verbose_name_plural = "Вендоры красок"

    def __str__(self):
        return self.name


class Paint(models.Model):
    vendor = models.ForeignKey(PaintVendor, verbose_name="Производитель краски", on_delete=models.PROTECT)
    name = models.CharField(verbose_name="Название краски", max_length=300)
    type = models.CharField(verbose_name="Тип краски", max_length=300, null=True, blank=True)
    details = models.CharField(verbose_name="Доп инфо", max_length=600, null=True, blank=True)
    color = models.CharField(verbose_name="Шеснадцатеричное RGB представление цвета", max_length=25, null=True,
                             blank=True)

    def __str__(self):
        if self.details:
            return "[%s] %s [%s]" % (self.details, self.name, self.type)
        return "%s [%s]" % (self.name, self.type)

    class Meta:
        ordering = ["vendor__name", "type", "details", "name"]
        verbose_name = "Краска"
        verbose_name_plural = "Краски"


class PaintInventory(models.Model):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.RESTRICT)
    paint = models.ForeignKey(Paint, verbose_name="Краска", on_delete=models.RESTRICT)
    wish = models.BooleanField(verbose_name="Нужна", default=False)
    has = models.BooleanField(verbose_name="Есть", default=False)

    def __str__(self):
        return "%s - %s" % (self.user.username, self.paint)

    class Meta:
        ordering = ["user", "has"]
        verbose_name = "Запас красок"
        verbose_name_plural = "Запасы красок"

work_in_progress/inventory/forms.py
from django import forms

from .models import Paint, PaintVendor, PaintInventory


class PaintInventoryManageForm(forms.Form):

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        vendors = PaintVendor.objects.all()
        self.vendors = []
        for vendor in vendors:
            paints = Paint.objects.filter(vendor=vendor)
            vendor_paints = ((x.id, str(x)) for x in paints)
            field = forms.MultipleChoiceField(
                label="Список красок",
                choices=vendor_paints,
                required=False,
                widget=forms.SelectMultiple(attrs={'size': '25'}))
            self.fields['paints_' + str(vendor.id)] = field
            paints_inventory = PaintInventory.objects.filter(user=user, paint__in=paints)

            if 'data' in kwargs:
                paints_inventory_has = ((x.id, str(x)) for x in paints)
            else:
                paints_inventory_has = ((x.paint.id, str(x.paint)) for x in paints_inventory.filter(has=True))

            field = forms.MultipleChoiceField(
                label="В наличии",
                choices=paints_inventory_has,
                required=False,
                widget=forms.SelectMultiple(attrs={'size': '25'}))
            self.fields['paints_has_from_vendor_' + str(vendor.id)] = field

            if 'data' in kwargs:
                paints_inventory_wish = ((x.id, str(x)) for x in paints)
            else:
                paints_inventory_wish = ((x.paint.id, str(x.paint)) for x in paints_inventory.filter(wish=True))

            field = forms.MultipleChoiceField(
                label="Надо купить",
                choices=paints_inventory_wish,
                required=False,
                widget=forms.SelectMultiple(attrs={'size': '25'}))
            self.fields['paints_wish_from_vendor_' + str(vendor.id)] = field
            self.vendors.append((vendor.id,
                                 vendor.name,
                                 'paints_' + str(vendor.id),
                                 'paints_has_from_vendor_' + str(vendor.id),
                                 'paints_wish_from_vendor_' + str(vendor.id)))

    def clean(self):
        cleaned_data = super().clean()
        paints_has = []
        paints_wish = []
        for v in self.vendors:
            vendor = PaintVendor.objects.get(id=v[0])
            if v[3] in cleaned_data:
                ids = list(map(lambda x: int(x), set(cleaned_data[v[3]])))
                selected_has_paints = Paint.objects.filter(vendor=vendor,
                                                           id__in=ids)
                paints_has.extend(selected_has_paints)
            if v[4] in cleaned_data:
                ids = list(map(lambda x: int(x), set(cleaned_data[v[4]])))
                selected_wish_paints = Paint.objects.filter(vendor=vendor,
                                                            id__in=ids)
                paints_wish.extend(selected_wish_paints)
        return {
            'has': paints_has,
            'wish': paints_wish
        }


class InventoryFilterForm(forms.Form):
    vendor = forms.ModelChoiceField(label="Производитель", queryset=PaintVendor.objects.all(), required=False)
    type = forms.ChoiceField(label="Тип", choices=(), required=False)
    status = forms.ChoiceField(label="Состояние",
                               choices=(('', '----'), ('wish', 'Надо купить'), ('has', 'В наличии')),
                               required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['type'].choices = (('', '----'), *set((x, x) for x in Paint.objects.all().values_list('type',
                                                                                                          flat=True)))

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data['wish'] = False
        cleaned_data['has'] = False
        if 'status' in cleaned_data:
            if cleaned_data['status'] == 'wish':
                cleaned_data['wish'] = True
            if cleaned_data['status'] == 'has':
                cleaned_data['has'] = True
        return cleaned_data

work_in_progress/templates/wip/base_form.html
{% extends 'wip/base.html' %}
{% block content %}
<h2>
    {{ title }}
</h2>
{% block back_link %}
{% endblock back_link %}
<div class="ui five column doubling stackable grid container">
    <div class="column"></div>
    <div class="column">
    {% block form %}
        <form action="{{ submit_url }}" class="ui form" method="post">
            {% csrf_token %}
            {% block form_fields %}
            {% endblock form_fields %}
            <div class="field">
                <button class="ui button" type="submit">{{ submit_label }}</button>
            </div>
        </form>
    {% endblock form %}
    </div>
    <div class="column"></div>
    <div class="column"></div>
</div>
{% block script %}
{% endblock script %}
{% endblock content %}

work_in_progress/templates/wip/inventory.html
{% extends 'wip/base.html' %}
{% load static %}
{% block content %}
    <script>
$(function() {
    function splitQuery() {
        const search = location.search;
        const res = {};
        search.replace('?','').split('&').filter(x => x.length > 0).forEach(param => {
            const k = param.split('=')[0];
            res[k] = param.split('=')[1];
        })
        return res;
    }
    function glueQuery(kv) {
        const res = [];
        Object.keys(kv).map(k => {
            res.push(k+'='+kv[k]);
        });
        return '?' + res.join('&');
    }
    $('#submit_filter_form').on('click', function(event) {
        event.preventDefault();
        const query = splitQuery();
        query['type'] = $('#id_type').val();
        query['vendor'] = $('#id_vendor').val();
        query['status'] = $('#id_status').val();
        location.href = glueQuery(query);
    })
})
</script>
{% if request.user.is_authenticated %}
        <a class="ui button" href="{% url 'wip:inventory_manage' %}">Управление</a>
{% endif %}
<div class="ui grid relaxed form ui">
    <div class="three wide column">
        {{ filter_form.as_div }}
        <a id="submit_filter_form">
            <i class="search icon"></i>
            Искать
        </a>
    </div>
</div>
<div class="ui cards" style="margin-bottom: 10px">
    {% for item in items %}
        <div class="ui card">
            {% if item.paint.color %}
                <div class="ui image" style="cursor: pointer;">
                    <div style="display:inline-block; width:100%;height: 64px; border: 1px solid black;background-color: {{ item.paint.color }}" ></div>
                </div>
            {% else %}
                <div class="ui image" style="cursor: pointer;">
                    <div style="display:inline-block; width:100%;height: 64px; border: 1px solid black;background-color: #7d7d7d" ></div>
                </div>
            {% endif %}
            <div class="content">
                <div class="header">
                    {{ item.paint.vendor.name }} {{ item.paint.name }}
                </div>
                <div class="meta">
                    {% if item.paint.type %}
                        <span>Тип: {{ item.paint.type }}</span>
                    {% endif %}
                    {% if item.paint.details %}
                        <span>Детали: {{ item.paint.details }}</span>
                    {% endif %}
                    {% if item.paint.color %}
                        <span>Цвет: {{ item.paint.color }}</span>
                    {% endif %}
                </div>
                <div class="extra content">
                    {% if item.has %}<span><i class="ui icon box"></i>Есть</span>{% endif %}
                    {% if item.wish %}<span><i class="ui icon shop"></i>Нужна</span>{% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

    <div>
        <p>{{ item.paint.vendor.name }}</p>
        <p>{{ item.paint.name }}</p>
        {% if item.paint.type %}
            <p>{{ item.paint.type }}</p>
        {% endif %}
        {% if item.paint.details %}
            <p>{{ item.paint.details }}</p>
        {% endif %}
        {% if item.paint.color %}
            <p>{{ item.paint.color }}</p>
        {% endif %}
        <p>{% if item.has %}Есть{% endif %}</p>
        <p>{% if item.wish %}Нужна{% endif %}</p>
    </div>

{% endblock content %}

work_in_progress/templates/wip/models.html
{% extends 'wip/base.html' %}
{% load wip_filters %}
{% load static %}
{% block content %}
<script>
$(function() {
    function splitQuery() {
        const search = location.search;
        const res = {};
        search.replace('?','').split('&').filter(x => x.length > 0).forEach(param => {
            const k = param.split('=')[0];
            res[k] = param.split('=')[1];
        })
        return res;
    }
    function glueQuery(kv) {
        const res = [];
        Object.keys(kv).map(k => {
            res.push(k+'='+kv[k]);
        });
        return '?' + res.join('&');
    }
    $('#submit_work_map_filter').on('click', function(event) {
        event.preventDefault();
        const query = splitQuery();
        query['work_map_year'] = $('#id_work_map_year').val();
        location.href = glueQuery(query);
    });
    $('#submit_filter_form').on('click', function(event) {
        event.preventDefault();
        const query = splitQuery();
        query['status'] = $('#id_status').val();
        query['group'] = $('#id_group').val();
        query['page_size'] = $('#id_page_size').val();
        location.href = glueQuery(query);
    })
})
</script>
<h2>
    Модели пользователя {{ user.username }}
</h2>
<div class="ui grid relaxed">
    <div class="six wide column">
        {% include 'wip/widgets/progress_map.html' %}
    </div>
    <div class="two wide column">
        {{ work_map_filter_form.as_p }}
        <a id="submit_work_map_filter">Применить</a>
    </div>
</div>
<div class="ui grid relaxed">
    {% for col in time_status_map %}
        <div class="three wide column">
        {% for item in col %}
            <div>{{ item.0 }} - {{ item.1|duration }}</div>
        {% endfor %}
        </div>
    {% endfor %}
    <div class="two wide column">
        {% for status_group, status_group_stats in units_count_by_status_group.items %}
            {% if status_group_stats is not None and status_group_stats.model is not None %}
                <div>{{ status_group }} - {{ status_group_stats.model }}</div>
            {% endif %}
        {% endfor %}
        {% if units_total is not None %}
            <div>Всего - {{ units_total }}</div>
        {% endif %}

        {% for status_group, status_group_stats in units_count_by_status_group.items %}
            {% if status_group_stats is not None and status_group_stats.terrain is not None %}
                <div>{{ status_group }}(террейн) - {{ status_group_stats.terrain }}</div>
            {% endif %}
        {% endfor %}
        {% if terrain_total is not None %}
            <div>Террейна всего - {{ terrain_total }}</div>
        {% endif %}
    </div>
</div>
<div class="ui grid relaxed form ui">
    <div class="three wide column">
        {{ filter_form.as_div }}
        <a id="submit_filter_form">
            <i class="search icon"></i>
            Искать
        </a>
    </div>
</div>
<div style="margin: 10px"></div>
{% if request.user.is_authenticated and request.user == user %}
<a href="{% url 'wip:add_model' %}">
<i class="icon plus square outline"></i>
    Добавить
</a>
{% endif %}
<div class="ui cards" style="margin-bottom: 10px">
    {% for model in models %}
        <div class="ui card">
            {% if model.get_last_image_url %}
                {% include 'wip/widgets/model_image.html' %}
            {% else %}
                <img src="{% static 'wip/img/default/ready.jpg' %}">
            {% endif %}
            <div class="content">
                <a class="header" href="">
                    <a href="{% url 'wip:progress' user.username model.id %}">{{ model.name }}</a>
                </a>
                <div class="meta">
                    <b style="color: #2d2d2d">{{ model.user_status.name }}</b> | {{ model.get_hours_spent|duration }}
                    {% if not model.user_status.is_initial and not model.user_status.is_final %}
                        | лежит уже {{ model.get_days_since_buy }} дней
                    {% endif %}
                </div>
                <div class="description">
                    {% if model.terrain == True %}
                        <div style="color: lightcoral">Террейн</div>
                        <div style="margin: 10px"></div>
                    {% endif %}
                    {% if model.unit_count > 1 %}
                        <div>Юнитов в модели: {{ model.unit_count }}</div>
                        <div style="margin: 10px"></div>
                    {% endif %}
                    {% if model.groups.exists %}
                        <div>Группы:
                            {% for group in model.groups.all %}
                                <span>{{ group.name }}</span>
                            {% endfor %}
                        </div>
                        <div style="margin: 10px"></div>
                    {% endif %}
                    {% if model.battlescribe_unit %}
                        <div>Категория BS: {{ model.battlescribe_unit.bs_category.name }}</div>
                        <div>Модель BS: {{ model.battlescribe_unit.name }}</div>
                        <div style="margin: 10px"></div>
                    {% endif %}
                    {% if model.kill_team %}
                        <div>Киллтим: {{ model.kill_team.name }}</div>
                        <div style="margin: 10px"></div>
                    {% endif %}
                </div>
            </div>
            <div class="extra content">
                {% if request.user.is_authenticated and request.user == user %}
                    <a href="{% url 'wip:edit_model' model.id %}">
                        <i class="pencil icon"></i>
                        Редактировать
                    </a>
                    {% if model.user_status.next %}
                        <div>
                            <a href="{% url 'wip:model_status_action' user.username model.id model.user_status.next.slug %}">
                                <i class="arrow alternate circle up outline icon"></i>
                                {{ model.user_status.next.transition_title }}
                            </a>
                        </div>
                    {% endif %}
                    {% if not model.user_status.is_final %}
                        <div>
                            <a href="{% url 'wip:add_progress' user.username model.id %}">
                                <i class="clock outline icon"></i>
                                Записать работу
                            </a>
                        </div>
                    {% endif %}
                    <div style="margin-top: 30px">
                        <a href="{% url 'wip:delete_model' model.id %}">
                            <i class="trash alternate outline icon"></i>
                            Удалить
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>
{% include 'wip/widgets/pagination.html' with page_obj=page_obj %}
<script>
$(document).ready(() => {
 $('#reset_filter_form').click(() => {
     window.location.href = window.location.href.split("?")[0];
 })
    $('a#submit').click(() => {
        $('#filter_form').submit();
    })
})
</script>
{% include 'wip/widgets/image_modal.html' %}
{% endblock %}

work_in_progress/templates/wip/progress.html
{% extends 'wip/base.html' %}
{% load wip_filters %}
{% block content %}
<h2>
    Прогресс по модели: {{ model.name }}
</h2>
<p>Потрачено всего:{{ total|duration }}</p>
<a href="{% url 'wip:models' user.username %}">Назад</a>
{% if request.user.is_authenticated and request.user == user %}
    <a href="{% url 'wip:add_progress' request.user.username model.id %}">Добавить время</a>
{% endif %}
<table class="celled ui table">
    <thead>
        <tr>
            <th>Дата</th>
            <th>В статусе</th>
            <th>Заголовок</th>
            <th>Подробно</th>
            <th>Время</th>
            <th>Картинки</th>
            <th></th>
        </tr>
    </thead>
<tbody>
    {% for progress in progress_items %}
        <tr>
            <td>{{ progress.datetime }}</td>
            <td>
                {% if progress.user_status %}
                    {{ progress.user_status }}
                {% endif %}
            </td>
            <td>{{ progress.title }}</td>
            <td>{{ progress.description }}</td>
            <td>{{ progress.time|duration }}</td>
            <td>
                {% for item in progress.modelimage_set.all %}
                    <div class="ui image" style="cursor: pointer;">
                        <img src="{{ item.image.url }}"
                            width="100"
                            height="100"
                            data-init-width="{{ model.get_last_image.width }}"
                            data-init-height="{{ model.get_last_image.height }}"
                        >
                    </div>
                {% endfor %}
            </td>
            <td>
                {% if request.user.is_authenticated and model.user == request.user %}
                <div>
                    <a class="item" href="{% url 'wip:edit_progress' request.user.username model.id progress.id %}">Редактировать</a>
                </div>
                <div style="margin-top: 20px" class="ui red label">
                    <a class="item" href="{% url 'wip:delete_progress' request.user.username model.id progress.id %}">Удалить</a>
                </div>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</tbody>
</table>
{% include 'wip/widgets/image_modal.html' %}
{% endblock %}